DROP TABLE IF EXISTS table1;
CREATE TABLE IF NOT EXISTS table1 ();
DROP TABLE IF EXISTS table2;
CREATE TABLE IF NOT EXISTS table2 ();
DROP TABLE IF EXISTS table3;
CREATE TABLE IF NOT EXISTS table3 ();